version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d"
    network_mode: host
  traefik:
    image: traefik:2.4
    restart: always
    command: --configfile=/etc/traefik/traefik.toml
    volumes:
      - ./traefik:/etc/traefik
      - ./traefik/certificates:/etc/traefik/certificates
    network_mode: host
volumes:
  postgres-data:
