name: Build and publish on Docker Hub

on:
  push:
    branches: [master]
  schedule:
  # New build every tuesday cause why not
   - cron:  '0 0 * * 2'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mauricethomas/soapbox-docker
          tags: |
            type=raw,value={{date 'YYYY-MM-DD'}}
            type=raw,value=latest
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}